###
# This is the place to override the opsworks_java cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_java/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Tomcat threadpool max size:
#
#normal['opsworks_java']['tomcat']['threadpool_max_threads'] = 150

normal['opsworks_java']['service_name'] = "article_server"
normal['opsworks_java']['base_dir'] = "/home/ubuntu/app"